projects:
  app:
    schemaPath: src/schema.graphql
    includes: ['**/*.graphql']
    extensions:
      endpoints:
        default: http://localhost:6001
  prisma:
    schemaPath: 'src/generated/prisma.graphql'
    extensions:
      prisma: database/prisma.yml
